"""
UploadCSV.py  (Part A.2)
========================
Fully automated pipeline that copies the annotated CSVs generated by
FormatCSV.py into the Neo4j import directory and bulk-loads them into the
database without any manual intervention.
 
Execution order
---------------
  1. Validate configuration (paths, credentials, source files).
  2. Copy CSVs from Neo4j_import/ to the Neo4j instance import folder.
  3. Stop the Neo4j Windows service and confirm the database is offline.
  4. Run neo4j-admin database import full.
  5. Start the Neo4j Windows service and wait for the database to accept
     Bolt connections.
  6. Verify import counts via the Python driver.
 
Requirements
------------
  - Neo4j must be installed as a Windows service. Run the following once
    from an Administrator PowerShell to register it: C:\neo4j\bin\neo4j.bat windows-service install
 
  - This script uses 'net stop neo4j' and 'net start neo4j' to manage the
    service lifecycle. No other application needs to be open.
  - The script works regardless of whether Neo4j is running or stopped when
    it is invoked.
 
Configuration
-------------
  All paths and credentials are read from a .env file in the project root.
 
Usage
-----
  1. Run FormatCSV.py to generate the Neo4j_import/ CSVs.
  2. python UploadCSV.py   (run as Administrator if net start/stop requires it)
"""

import os
import shutil
import subprocess
import sys
import time
from pathlib import Path
import requests
from dotenv import load_dotenv
from neo4j import GraphDatabase

# =============================================================================
# CONFIGURATION
# =============================================================================

load_dotenv()

NEO4J_URI       = os.getenv("NEO4J_URI",      "bolt://localhost:7687")
NEO4J_USER      = os.getenv("NEO4J_USER",     "neo4j")
NEO4J_PASSWORD  = os.getenv("NEO4J_PASSWORD", "")
DATABASE_NAME   = os.getenv("NEO4J_DATABASE", "neo4j")
NEO4J_DBMS_ROOT      = Path(os.getenv("NEO4J_DBMS_ROOT", ""))

# Define the source directory with data to import.
SOURCE_DIR = Path('Neo4j_import')

# Timeouts (seconds)
STOP_TIMEOUT  = 60    # max time to wait for the DB to go offline after stop
START_TIMEOUT = 120   # max time to wait for the DB to come online after start
POLL_INTERVAL = 5     # seconds between each connectivity probe

# Force UTF-8 output on Windows to avoid encoding errors in the console.
if sys.platform == "win32":
    os.system("chcp 65001 > nul")

# =============================================================================
# DERIVED PATHS
# =============================================================================

NEO4J_IMPORT_DIR = NEO4J_DBMS_ROOT / "import"
NEO4J_ADMIN_BIN  = NEO4J_DBMS_ROOT / "bin" / "neo4j-admin.bat"


# =============================================================================
# STEP 0 -- VALIDATE CONFIGURATION
# =============================================================================
 
def validate_configuration() -> None:
    """
    Abort early if any required path or credential is missing or points to a
    location that does not exist on disk.
    """
    errors = []
 
    if not NEO4J_DBMS_ROOT or not NEO4J_DBMS_ROOT.exists():
        errors.append(f"NEO4J_DBMS_ROOT not found: '{NEO4J_DBMS_ROOT}'")
    if not NEO4J_ADMIN_BIN.exists():
        errors.append(f"neo4j-admin.bat not found: '{NEO4J_ADMIN_BIN}'")
    if not SOURCE_DIR.exists():
        errors.append(
            f"Source CSV directory not found: '{SOURCE_DIR}'. "
            "Run FormatCSV.py first."
        )
    if not NEO4J_PASSWORD:
        errors.append("NEO4J_PASSWORD is not set in .env.")
 
    if errors:
        print("[ERROR] Configuration problems detected:")
        for err in errors:
            print(f"        - {err}")
        sys.exit(1)
 
    print("[OK] Configuration validated.")
 
 
# =============================================================================
# STEP 1 -- COPY CSVs INTO THE NEO4J IMPORT DIRECTORY
# =============================================================================
 
def copy_csvs_to_import_dir() -> None:
    """
    Copy all CSV files from SOURCE_DIR into the Neo4j instance import folder.
    Creates the import directory if it does not already exist.
    Files already present in the destination are overwritten silently.
    """
    if not NEO4J_IMPORT_DIR.exists():
        print(f"[INFO] Import directory not found, creating: {NEO4J_IMPORT_DIR}")
        try:
            NEO4J_IMPORT_DIR.mkdir(parents=True, exist_ok=True)
            print("[OK] Import directory created.")
        except OSError as exc:
            print(f"[ERROR] Could not create import directory: {exc}")
            print("        Check that NEO4J_DBMS_ROOT is correct and you have write permissions.")
            sys.exit(1)
 
    csv_files = list(SOURCE_DIR.glob("*.csv"))
    if not csv_files:
        print(f"[ERROR] No CSV files found in {SOURCE_DIR}.")
        sys.exit(1)
 
    print(f"[INFO] Copying {len(csv_files)} CSV files -> {NEO4J_IMPORT_DIR}")
    for csv_file in csv_files:
        shutil.copy2(csv_file, NEO4J_IMPORT_DIR / csv_file.name)
        print(f"       -> {csv_file.name}")
    print("[OK] All files copied.")
 
 
# =============================================================================
# CONNECTIVITY PROBES
# =============================================================================
 
def _is_db_reachable() -> bool:
    """
    Return True if a Bolt connection can be established to the database,
    False otherwise. Never raises exceptions.
    """
    try:
        driver = GraphDatabase.driver(NEO4J_URI, auth=(NEO4J_USER, NEO4J_PASSWORD))
        driver.verify_connectivity()
        driver.close()
        return True
    except Exception:
        return False
 
 
def wait_until_offline(timeout: int = STOP_TIMEOUT) -> None:
    """
    Block until the database stops accepting Bolt connections or the timeout
    expires. Exits the process if the database does not go offline in time.
 
    Parameters
    ----------
    timeout : int
        Maximum seconds to wait for the database to become unreachable.
    """
    print(f"[INFO] Waiting for Neo4j to go offline (timeout: {timeout}s)...")
    deadline = time.time() + timeout
    while time.time() < deadline:
        if not _is_db_reachable():
            print("[OK] Neo4j is offline.")
            return
        print(f"       Still reachable -- retrying in {POLL_INTERVAL}s...")
        time.sleep(POLL_INTERVAL)
    print("[ERROR] Neo4j is still reachable after the stop timeout.")
    print("        Stop the service manually: net stop neo4j")
    sys.exit(1)
 
 
def wait_until_online(timeout: int = START_TIMEOUT) -> None:
    """
    Block until the database accepts a Bolt connection or the timeout expires.
    Exits the process if the database does not come online in time.
 
    Parameters
    ----------
    timeout : int
        Maximum seconds to wait for the database to become reachable.
    """
    print(f"[INFO] Waiting for Neo4j to come online (timeout: {timeout}s)...")
    deadline = time.time() + timeout
    while time.time() < deadline:
        if _is_db_reachable():
            print("[OK] Neo4j is online and accepting connections.")
            return
        print(f"       Not yet reachable -- retrying in {POLL_INTERVAL}s...")
        time.sleep(POLL_INTERVAL)
    print("[ERROR] Neo4j did not come online within the start timeout.")
    print("        Start the service manually: net start neo4j")
    sys.exit(1)
 
 
# =============================================================================
# STEPS 2 & 4 -- STOP / START THE WINDOWS SERVICE
# =============================================================================
 
def stop_database() -> None:
    """
    Stop the Neo4j Windows service via 'net stop neo4j', then block until
    the Bolt port is confirmed unreachable.
 
    If the service is already stopped, 'net stop' exits with code 2. This is
    treated as a non-fatal warning because the desired end state (offline) is
    already reached.
    """
    print("[INFO] Stopping Neo4j Windows service...")
 
    # If the database is already offline there is nothing to stop.
    if not _is_db_reachable():
        print("[OK] Neo4j is already offline. Skipping stop.")
        return
 
    try:
        subprocess.run(
            ["net", "stop", "neo4j"],
            check=True,
            capture_output=False,
            text=True,
        )
    except subprocess.CalledProcessError as exc:
        # Exit code 2 means the service was not running -- that is fine.
        if exc.returncode == 2:
            print("[WARN] Service was not running. Continuing.")
        else:
            print(f"[ERROR] 'net stop neo4j' exited with code {exc.returncode}.")
            print("        Try running this script as Administrator.")
            sys.exit(1)
 
    wait_until_offline()
 
 
def start_database() -> None:
    """
    Start the Neo4j Windows service via 'net start neo4j', then block until
    a Bolt connection is successfully established.
 
    If the service is already running, 'net start' exits with code 2. This is
    treated as a non-fatal warning because the desired end state (online) is
    already reached.
    """
    print("[INFO] Starting Neo4j Windows service...")
 
    # If the database is already reachable there is nothing to start.
    if _is_db_reachable():
        print("[OK] Neo4j is already online. Skipping start.")
        return
 
    try:
        subprocess.run(
            ["net", "start", "neo4j"],
            check=True,
            capture_output=False,
            text=True,
        )
    except subprocess.CalledProcessError as exc:
        # Exit code 2 means the service was already running -- that is fine.
        if exc.returncode == 2:
            print("[WARN] Service was already running. Continuing.")
        else:
            print(f"[ERROR] 'net start neo4j' exited with code {exc.returncode}.")
            print("        Try running this script as Administrator.")
            sys.exit(1)
 
    wait_until_online()
 
 
# =============================================================================
# STEP 3 -- RUN NEO4J-ADMIN DATABASE IMPORT
# =============================================================================
 
def run_neo4j_admin_import() -> None:
    """
    Execute neo4j-admin database import full with all A.1 node and
    relationship CSV files.
 
    The --overwrite-destination flag allows re-running the import on an
    existing database. The database is guaranteed to be stopped at this point
    because stop_database() blocks until offline.
 
    Note on EDITION_OF: Conference and Workshop editions are kept in two
    separate files because they resolve to different node label ID spaces.
    Merging them into one file would cause neo4j-admin to fail.
    """
    command = [
        str(NEO4J_ADMIN_BIN),
        "database", "import", "full", DATABASE_NAME,
        "--verbose",
        # -- Node files --
        r"--nodes=Paper=import\nodes_papers.csv",
        r"--nodes=Author=import\nodes_authors.csv",
        r"--nodes=Keyword=import\nodes_keywords.csv",
        r"--nodes=Journal=import\nodes_journals.csv",
        r"--nodes=Volume=import\nodes_volumes.csv",
        r"--nodes=Conference=import\nodes_conferences.csv",
        r"--nodes=Workshop=import\nodes_workshops.csv",
        r"--nodes=Edition=import\nodes_editions.csv",
        # -- Relationship files --
        r"--relationships=WROTE=import\rels_wrote.csv",
        r"--relationships=CITES=import\rels_cites.csv",
        r"--relationships=HAS_KEYWORD=import\rels_has_keyword.csv",
        r"--relationships=REVIEWED=import\rels_reviewed.csv",
        r"--relationships=PUBLISHED_IN_VOLUME=import\rels_paper_volume.csv",
        r"--relationships=BELONGS_TO=import\rels_volume_journal.csv",
        r"--relationships=PRESENTED_IN=import\rels_paper_edition.csv",
        r"--relationships=EDITION_OF=import\rels_edition_conference.csv",
        r"--relationships=EDITION_OF=import\rels_edition_workshop.csv",
        "--overwrite-destination",
    ]
 
    print("[INFO] Starting neo4j-admin bulk import...")
    print(f"       Target database : {DATABASE_NAME}")
    print(f"       neo4j-admin     : {NEO4J_ADMIN_BIN}")
    print()
 
    start = time.time()
    try:
        subprocess.run(
            command,
            check=True,
            capture_output=False,
            text=True,
            cwd=str(NEO4J_DBMS_ROOT),
        )
        print(f"\n[OK] Import completed in {time.time() - start:.1f} seconds.")
 
    except subprocess.CalledProcessError as exc:
        print(f"\n[ERROR] neo4j-admin exited with code {exc.returncode}.")
        print("        Review the output above for import errors.")
        sys.exit(1)
 
    except FileNotFoundError:
        print("\n[ERROR] neo4j-admin.bat could not be executed.")
        print("        Verify that Java 21 is installed and JAVA_HOME is set correctly.")
        sys.exit(1)
 
    except KeyboardInterrupt:
        print("\n[WARN] Import interrupted by user.")
        sys.exit(1)
 
 
# =============================================================================
# STEP 5 -- POST-IMPORT VERIFICATION
# =============================================================================
 
def verify_import() -> None:
    """
    Run count queries against every node label and relationship type to confirm
    that the import produced a non-empty graph.
 
    Prints a warning next to any label or type that returned zero rows, as
    that would indicate a silent failure during import.
    """
    print("[INFO] Running post-import verification...")
 
    try:
        driver = GraphDatabase.driver(NEO4J_URI, auth=(NEO4J_USER, NEO4J_PASSWORD))
        with driver.session(database=DATABASE_NAME) as session:
            node_counts = session.run(
                "MATCH (n) RETURN labels(n)[0] AS label, count(n) AS total "
                "ORDER BY total DESC"
            ).data()
            rel_counts = session.run(
                "MATCH ()-[r]->() RETURN type(r) AS rel, count(r) AS total "
                "ORDER BY total DESC"
            ).data()
        driver.close()
    except Exception as exc:
        print(f"[ERROR] Verification query failed: {exc}")
        sys.exit(1)
 
    empty_labels = []
    empty_rels   = []
 
    print("\n[OK] Import verification:")
    print("     Nodes:")
    for row in node_counts:
        warning = "  <-- EMPTY" if row['total'] == 0 else ""
        print(f"       {row['label']:20s}  {row['total']:>10,}{warning}")
        if row['total'] == 0:
            empty_labels.append(row['label'])
 
    print("     Relationships:")
    for row in rel_counts:
        warning = "  <-- EMPTY" if row['total'] == 0 else ""
        print(f"       {row['rel']:24s}  {row['total']:>10,}{warning}")
        if row['total'] == 0:
            empty_rels.append(row['rel'])
 
    if empty_labels or empty_rels:
        print("\n[WARN] Some labels or relationship types imported zero rows.")
        print("       Review the neo4j-admin output above for import warnings.")
    else:
        print("\n[OK] All node labels and relationship types contain data.")
 
 
# =============================================================================
# MAIN
# =============================================================================
 
def main() -> None:
    print("=" * 60)
    print("  SDM Lab A.2 -- Neo4j Bulk Import (automated)")
    print("=" * 60)
    print()
 
    validate_configuration()
    print()
 
    copy_csvs_to_import_dir()
    print()
 
    stop_database()
    print()
 
    run_neo4j_admin_import()
    print()
 
    start_database()
    print()
 
    verify_import()
 
    print("\n[INFO] Next steps:")
    print(f"  1. Open Neo4j Browser at http://localhost:7474")
    print(f"  2. Connect to database: {DATABASE_NAME}")
    print("  3. Now, you can start querying and creating indexes if required.")
 
 
if __name__ == '__main__':
    main()